# Generated by Django 2.2.9 on 2021-04-05 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_poststatistic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poststatistic',
            options={'ordering': ['-views']},
        ),
        migrations.RemoveField(
            model_name='poststatistic',
            name='date',
        ),
    ]
