# Generated by Django 2.2.9 on 2021-04-05 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0024_auto_20210405_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Просмотры'),
        ),
        migrations.DeleteModel(
            name='PostStatistic',
        ),
    ]
